export enum Time {
  Milliseconds = 1,
  Seconds = 1_000 * Milliseconds,
  Minutes = 60 * Seconds,
  Hours = 60 * Minutes,
  Days = 24 * Hours,
  Weeks = 7 * Days,
  Months = (365.2425 / 12) * Days,
  Years = 365.2425 * Days,
}

export enum Interval {
  Hourly = Time.Hours,
  Bidaily = 2 * Time.Days,
  Daily = Time.Days,
  Triweekly = 3 * Time.Days,
  Weekly = Time.Weeks,
  Biweekly = 2 * Time.Weeks,
  Monthly = Time.Months,
  Quarterly = 3 * Time.Months,
  Biannually = 6 * Time.Months,
  Annually = Time.Years,
  Biennially = 2 * Time.Years,
  Decennially = 10 * Time.Years,
  Centennially = 100 * Time.Years,
}

export enum HttpStatus {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  REQUEST_ENTITY_TOO_LARGE = 413,
  REQUEST_URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507,
  LOOP_DETECTED = 508,
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export enum ResponseMessages {
  ARRAY_FAIL = 'Request body must be an array',
  DEL_OK = 'Item deleted successfully',
  DELS_OK = 'Items deleted successfully',
  ID_FAIL = 'Invalid ID',
  IDS_FAIL = 'Invalid IDs',
  INTERNAL_SERVER = "Internal Server Error",
  ITEM_FAIL = 'Item not found',
  ITEMS_FAIL = 'No matching items found',
  NO_ID = 'No ID Param Found',
  NO_PAYLOAD = 'No Payload Found',
  PAYLOAD_FAIL = 'Invalid Payload (fields)',
  SOFT_DEL_FAIL = 'Unable to soft delete the item',
  SOFT_DEL_OK = 'Item soft deleted successfully',
  SOFT_DELS_OK = `Items soft deleted successfully`,
}
