/**
 * Enum for error codes.
 *
 * @enum {string}
 */
export enum ErrorCodes {
  BAD_REQUEST = 'BAD_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
  INTERNAL_SERVER = 'INTERNAL_SERVER_ERROR',
  NO_CONTENT = 'NO_CONTENT',
  NOT_FOUND = 'NOT_FOUND',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
}
