swagger: '2.0'
info:
  version: '0.1'
  title: 'Cache API'
basePath: '/v0.1'
schemes:
  - 'http'
paths:
  /cache:
    post:
      summary: 'Creates a new cache record'
      consumes:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Cache object that needs to be added'
          required: true
          schema:
            $ref: '#/definitions/Cache'
      responses:
        '200':
          description: 'successful operation'
        '400':
          description: 'Invalid input'
    get:
      summary: 'Retrieves all cache records'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'successful operation'
  /cache/{cacheId}:
    get:
      summary: 'Retrieves a specific cache record by ID'
      produces:
        - 'application/json'
      parameters:
        - name: 'cacheId'
          in: 'path'
          description: 'ID of cache record to retrieve'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'successful operation'
        '404':
          description: 'Cache record not found'
    put:
      summary: 'Updates a specific cache record by ID'
      consumes:
        - 'application/json'
      parameters:
        - name: 'cacheId'
          in: 'path'
          description: 'ID of cache record that needs to be updated'
          required: true
          type: 'integer'
          format: 'int64'
        - in: 'body'
          name: 'body'
          description: 'Cache object that needs to be updated'
          required: true
          schema:
            $ref: '#/definitions/Cache'
      responses:
        '200':
          description: 'successful operation'
        '400':
          description: 'Invalid input'
        '404':
          description: 'Cache record not found'
    delete:
      summary: 'Deletes a specific cache record by ID'
      produces:
        - 'application/json'
      parameters:
        - name: 'cacheId'
          in: 'path'
          description: 'ID of cache record to delete'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'successful operation'
        '404':
          description: 'Cache record not found'
  /meta/cache:
    get:
      summary: 'Retrieves metadata about the cache model'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'successful operation'
definitions:
  Cache:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      contents:
        type: 'json'
