swagger: '2.0'
info:
  version: '0.1'
  title: 'Profile API'
basePath: '/v0.1'
schemes:
  - 'http'
paths:
  /profile:
    post:
      summary: 'Creates a new profile record'
      consumes:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Profile object that needs to be added'
          required: true
          schema:
            $ref: '#/definitions/Profile'
      responses:
        '200':
          description: 'successful operation'
        '400':
          description: 'Invalid input'
    get:
      summary: 'Retrieves all profile records'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'successful operation'
  /profile/{profileId}:
    get:
      summary: 'Retrieves a specific profile record by ID'
      produces:
        - 'application/json'
      parameters:
        - name: 'profileId'
          in: 'path'
          description: 'ID of profile record to retrieve'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'successful operation'
        '404':
          description: 'Profile record not found'
    put:
      summary: 'Updates a specific profile record by ID'
      consumes:
        - 'application/json'
      parameters:
        - name: 'profileId'
          in: 'path'
          description: 'ID of profile record that needs to be updated'
          required: true
          type: 'integer'
          format: 'int64'
        - in: 'body'
          name: 'body'
          description: 'Profile object that needs to be updated'
          required: true
          schema:
            $ref: '#/definitions/Profile'
      responses:
        '200':
          description: 'successful operation'
        '400':
          description: 'Invalid input'
        '404':
          description: 'Profile record not found'
    delete:
      summary: 'Deletes a specific profile record by ID'
      produces:
        - 'application/json'
      parameters:
        - name: 'profileId'
          in: 'path'
          description: 'ID of profile record to delete'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'successful operation'
        '404':
          description: 'Profile record not found'
  /meta/profile:
    get:
      summary: 'Retrieves metadata about the profile model'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'successful operation'
definitions:
  Profile:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      email:
        type: 'string'
      firstName:
        type: 'string'
      lastName:
        type: 'string'
      bio:
        type: 'string'
      city:
        type: 'string'
      country:
        type: 'string'
      phone:
        type: 'string'
      avatar:
        type: 'string'
      gender:
        type: 'enum'
      dob:
        type: 'date'
      facebook:
        type: 'string'
      instagram:
        type: 'string'
      threads:
        type: 'string'
      twitter:
        type: 'string'
      linkedIn:
        type: 'string'
      github:
        type: 'string'
      youtube:
        type: 'string'
